included:
  - Sources
  - Package.swift

line_length: 200
file_length:
  warning: 500
  ignore_comment_only_lines: true
type_body_length: 300

file_header:
  severity: error
  required_pattern: |
                    \/\/ SPDX-License-Identifier: MIT
                    \/\/ Copyright 2023, Jamf

opt_in_rules:
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_direct_init
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - first_where
  - flatmap_over_map_reduce
  - last_where
  - strict_fileprivate
  - test_case_accessibility
  - file_header

analyzer_rules:
  - unused_declaration
  - unused_import
